### ISSUE TITLE
Some bugs in template script characterisations commands

### ISSUE THREAD

**Issue by smartinm** [flexiant/concerto#13]
- In `templates create_template_script` command:
  - The script id (`--script_id`) is a required parameter.
  - The script parameter values (`--parameter_values`) is an optional parameter.

```
$ concerto bl templates create_template_script --template_id 569f6f086f4cd372ef00000e --type operational --parameter_values {test: "value"}
FATA[0000] HTTP request failed: [script_id can't be blank] 
```
- The `templates delete_template_script` command report "Incorrect Usage" using the required parameters.

```
$ concerto bl templates delete_template_script --template_id 56533352fa334e89f400024d --id 56a72fa80338aa0005000030
Incorrect Usage.

$ concerto bl templates delete_template_script --template_id 56533352fa334e89f400024d --id 56a72fa80338aa0005000030 --script_id 55b0917d10c0ecc351000769
Incorrect Usage.
```
- The parameter `--template_id` is required in `templates list_template_servers` command.

```
$ concerto bl templates list_template_servers
FATA[0010] HTTP request failed: [Template not found]    
```

**Comment by odacremolbap** [comment]
`create_template_script` requires now `template_id`, `type` and `script_id`
`delete_template_script` requires `template_id` and `id` (script/template association id)
`list_template_servers` requires now `template_id`
