### ISSUE TITLE
Reports commands is using an incorrect webservice

### ISSUE THREAD

**Issue by smartinm** [flexiant/concerto#18]
The `settings reports list` and `settings reports show_report` commands is using the admin webservice controller (`/v1/admin/reports`) instead of the user settings controller (`/v1/settings/reports`).

Settings command should return information about the reports related to the account group, not to all the account groups of the tenant.

```
$ concerto settings reports list
REPORT ID                  YEAR           MONTH          START TIME                      END TIME                        SERVER SECONDS   CLOSED
569fa1a86f4cd397920007ca   2016           January        2015-12-31 23:00:00 +0000 UTC   2016-01-31 23:00:00 +0000 UTC   1.8633562e+06    false
569fa1a86f4cd397920007c7   2016           January        2015-12-31 23:00:00 +0000 UTC   2016-01-31 23:00:00 +0000 UTC   6.1575345e+06    false
569fa1a86f4cd397920007c5   2016           January        2015-12-31 23:00:00 +0000 UTC   2016-01-31 23:00:00 +0000 UTC   8.0208905e+06    false
569fa1a86f4cd397920007c3   2015           December       2015-11-30 23:00:00 +0000 UTC   2015-12-31 23:00:00 +0000 UTC   2.4478152e+06    true
569fa1a86f4cd397920007c0   2015           December       2015-11-30 23:00:00 +0000 UTC   2015-12-31 23:00:00 +0000 UTC   2.0158152e+06    true
569fa1a86f4cd397920007be   2015           December       2015-11-30 23:00:00 +0000 UTC   2015-12-31 23:00:00 +0000 UTC   4.4636305e+06    true
```

**Comment by abligh** [comment]
The `SERVER SECONDS` column is going to be difficult to parse either by machine or by human. Given the start time and end time are in human readable form (rather than seconds from epoch) how about doing what Docker does and say "4d3h1m" or similar.

**Comment by smartinm** [comment]
I believe this is a significant improvement, I have created a new issue for your comment.
